### ISSUE TITLE
Team images broken on Team page 

### ISSUE THREAD

**Issue by fucha-co** [fucha-co/ns#7]
- I updated nearly all images in the site to use the new Astro Images (and it wasn't fun or as awesome as i thought; of note height and widths must be set on all new Astro Images otherwise they fail)
- i think i know why the images are broken in [...page].astro but i don't know how to rewrite the images here (which use the ContentMedia Component _and_ data from posts.json)

**Comment by shivjm** [comment]
I’m not able to access `/our-team/` at all. Do you see this error too?
```
TypeError: Cannot read properties of undefined (reading 'data')
    at Object.default (/site/src/pages/our-team/[...page].astro:64:18)
    at new AstroComponentInstance (/site/node_modules/astro/dist/runtime/server/render/astro/instance.js:15:32)
    at Module.createAstroComponentInstance (/site/node_modules/astro/dist/runtime/server/render/astro/instance.js:52:20)
    at Module.renderComponent (/site/node_modules/astro/dist/runtime/server/render/component.js:303:12)
    at /site/src/pages/our-team/[...page].astro:1:1
    at [...page] (/site/node_modules/astro/dist/runtime/server/astro-component.js:19:12)
    at renderPage (file:///site/node_modules/astro/dist/runtime/server/render/page.js:96:36)
    at renderPage (file:///site/node_modules/astro/dist/core/render/core.js:49:24)
    at renderPage (file:///site/node_modules/astro/dist/core/render/dev/index.js:128:16)
    at async handleRoute (file:///site/node_modules/astro/dist/vite-plugin-astro-server/route.js:162:20)
```
I can see it says `page.data.map` but I’m not sure where that’s supposed to come from.

**Comment by fucha-co** [comment]
- i never got a notification about your reply, so i only just saw it now (16hrs later)
- either way, closing with https://github.com/fucha-co/ns/commit/79d81fd6d0e3f288df47fc5c18d01518875e0452
